# Personal blog with RSS feed and tags
base_url = "https://apparently-typ.ing"
title = "> Apparently Typing"
description = "The nerdy musings of an internet denizen"
theme = "tanuki"
compile_sass = true
build_search_index = true
generate_feeds = false

taxonomies = [
    { name = "tags", feed = false },
]

[extra]
mode = "blog"

[extra.author]
name=""
bio="A nerdy technology focused internet denizen"

# [extra.social]
# github="http://github.com/jacobsky"

[extra.hero]
title = "> Apparently Typing"
subtitle = "Musings of a nerdy internet denizen"

[extra.hero.cta]
text = "Read my musings"
url = "/blog/"

[[extra.nav]]
name = "Blog"
url = "/blog/"

[[extra.nav]]
name = "About"
url = "/about/"

# [[extra.nav]]
# name = "Projects"
# url = "/projects/"
